using Terminal.Gui.ViewBase;
using Terminal.Gui.Views;

namespace FocusBlock.Tui.Views;

/// <summary>
/// Modal dialog that shows a challenge and validates the text the user types by hand.
/// </summary>
/// <remarks>
/// <para>
/// This dialog is the friction step before an early stop. It only renders the challenge
/// and checks that the typed text matches it; it does not generate the challenge (that is
/// <see cref="Services.ChallengeSystem"/>) and it does not check the password, which is the
/// real security gate.
/// </para>
/// </remarks>
public class ChallengeDialog : Dialog
{
    private readonly string _challenge;

    /// <summary>Gets the label that displays the challenge to type.</summary>
    public Label ChallengeLabel { get; }

    /// <summary>Gets the field where the user types the challenge.</summary>
    public TextField InputField { get; }

    /// <summary>Gets the button that confirms the typed challenge.</summary>
    public Button OkButton { get; }

    /// <summary>Gets the button that cancels the early stop.</summary>
    public Button CancelButton { get; }

    /// <summary>Creates the dialog for the given <paramref name="challenge"/>.</summary>
    /// <param name="challenge">The challenge text already generated by <c>ChallengeSystem</c>.</param>
    public ChallengeDialog(string challenge)
    {
        _challenge = challenge;
        Title = "Early stop";
        ChallengeLabel = new Label { Text = $"Type this: {challenge}", X = 1, Y = 1 };
        InputField = new TextField { X = 1, Y = 3, Width = Dim.Fill(2) };
        OkButton = new Button { Text = "OK" };
        CancelButton = new Button { Text = "Cancel" };

        Add(ChallengeLabel, InputField);
        AddButton(OkButton);
        AddButton(CancelButton);
    }

    /// <summary>Checks whether the typed text matches the challenge (ordinal, case-sensitive).</summary>
    /// <returns><see langword="true"/> when the trimmed input equals the challenge.</returns>
    public bool ValidateInput() =>
        string.Equals(InputField.Text?.Trim(), _challenge, StringComparison.Ordinal);
}